# Generated by Django 3.2.5 on 2021-07-12 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover', models.FileField(upload_to='files/post_cover/')),
                ('description', models.CharField(max_length=300)),
                ('publish_at', models.DateField(default=datetime.datetime(2021, 7, 12, 10, 33, 12, 251403))),
                ('event_at', models.DateField()),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
