# Generated by Django 3.2.5 on 2021-07-20 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210712_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 10, 38, 48, 620821)),
        ),
    ]
