# Generated by Django 3.2.5 on 2021-07-20 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.FileField(upload_to='static/files/category_cover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='static/files/post_cover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 10, 57, 24, 611640)),
        ),
    ]
