# Generated by Django 3.2.5 on 2021-07-20 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210720_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='files/post_cover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 11, 13, 30, 418422)),
        ),
    ]
