# Generated by Django 3.2.5 on 2021-07-27 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210720_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FileField(upload_to='static/files/post_cover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 27, 6, 25, 7, 540065)),
        ),
    ]
