# Generated by Django 3.2.5 on 2021-07-27 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 27, 7, 5, 54, 839259)),
        ),
    ]
